import { COLORS } from "@/constants/colors";
import { Dimensions, Platform, StyleSheet } from "react-native";
const { height, width } = Dimensions.get("window");

export const componentStyle = StyleSheet.create({
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    borderRadius: height*0.03,
    paddingHorizontal: 15,
    height: height * 0.06,
    width: "90%",
    marginVertical: height * 0.01,
    borderWidth: height * 0.005,
    borderColor: COLORS.red,
  },
  inputIcon: {
    width: "6%",
    height: "50%",
    marginRight: 10,
    tintColor: "#A9A9A9",
  },
  inputText: {
    flex: 1,
    fontSize: height * 0.016,
    color: COLORS.textMuted,
    fontFamily: "Poppins-SemiBold",
  },
    iconPerfilContainer: {
    height: height * 0.15,
    width: height * 0.15,
    borderRadius: (height * 0.15) / 2,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
    marginBottom: 10,
    alignSelf: "center",
    position: "relative",
    borderWidth: 4,
    borderColor: COLORS.red,
  },
  iconPerfilImage: {
    height: "100%",
    width: "100%",
    borderRadius: (height * 0.15) / 2,
    resizeMode: "contain",
  },
  editButtonContainer: {
    position: "absolute",
    bottom: 0,
    right: -height * 0.15 * 0.1,
    height: height * 0.15 * 0.35,
    width: height * 0.15 * 0.35,
    backgroundColor: COLORS.black,
    borderRadius: "100%",
    borderWidth: height * 0.004,
    borderColor: COLORS.gold,
    justifyContent: "center",
    alignItems: "center",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  editButtonIcon: {
    width: "90%",
    height: "90%",
    resizeMode: "contain",
    tintColor: COLORS.gold,
  },
   titleBarContainer: {
      width: '100%',
      height: 100,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'transparent',
      marginTop: 0,
      marginBottom: 20,
      overflow: 'hidden',
  },
  titleBackground: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: -1,
  },
    welcomeTitle: {
      fontSize: 24,
      fontFamily: 'Poppins-SemiBold',
      color: COLORS.gold,
      textAlign: 'center',
      zIndex: 1,
      paddingBottom: 10,
  },
    codeInputContainer: {
    flexDirection: "row",
    gap: height * 0.012,
    justifyContent: "center",
    marginVertical: height * 0.012,
    width: "100%",
  },
  codeInputBox: {
    width: width * 0.09,
    height: width * 0.11,
    maxWidth:height * 0.08,
    maxHeight: height * 0.1,
    backgroundColor: COLORS.primaryDark,
    borderRadius: 10,
    color: COLORS.gold,
    marginTop: height * 0.01,
    fontSize: height * 0.03,
    textAlign: "center",
    fontFamily: "Poppins-SemiBold",
  },
  box: {
    backgroundColor: COLORS.primary,
    borderRadius: 30,
    alignSelf: "center",
    boxShadow: "0px 4px 40px 40px rgba(0, 0, 0, 0.20)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 15.8,
    elevation: 16,
    overflow: "visible",
  },
  boxDark: {
    backgroundColor: COLORS.primaryDark,
    borderColor: COLORS.red,
    borderWidth: height * 0.007,
    borderRadius: 30,
    alignSelf: "center",
    overflow: "visible",
    padding: height * 0.03,
  },
  popupOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)"
  },
  popup: {
    width: "84%",
    padding: 24,
    borderRadius: 20,
    backgroundColor: COLORS.white,
    borderColor: COLORS.red,
    borderWidth: height * 0.007,
    alignItems: "center",
  },
  popupText: {
    color: COLORS.textMuted,
    fontSize: height * 0.018,
    fontFamily: "Poppins-SemiBold",
    textAlign: "center",
  },
  exclamationIcon: {
    width: height * 0.05,
    height: height * 0.05,
    marginBottom: height * 0.02,
    alignItems: "center",
  },
  couponContainer: {
    width: width * 0.75,
    marginVertical: height * 0.02,
    borderRadius: height * 0.025,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  couponBox: {
    backgroundColor: COLORS.gold,
    borderRadius: height * 0.02,
    paddingHorizontal: width * 0.05,
    paddingVertical: height * 0.02,
    minHeight: height * 0.10,
    justifyContent: 'center',
  },
  coupomContentContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  coupomTextContainer: {
    flex: 1,
    justifyContent: 'center',
    marginRight: width * 0.05,
  },
  coupomTitle: {
    fontSize: height * 0.030,
    paddingBottom: height * 0.004,
    fontWeight: '900',
    color: '#000000',
    fontFamily: 'Poppins-SemiBold',
  },
  coupomSubtitle: {
    fontSize: height * 0.013,
    color: '#000000',
    fontFamily: 'Poppins-Regular',
    lineHeight: height * 0.02,
  },
  coupomIconContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  coupomIcon: {
    width: height * 0.08,
    height: height * 0.08,
  },
    userPipokaContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: COLORS.primaryDark,
    borderRadius: height,
    width: "55%",
    marginBottom: height * 0.005,
    position: "relative",
  },
  UserPipokaTextWrapper: {
    flex: 1,
  },
  userPipokaBaseText: {
    fontSize: height * 0.012,
    color: COLORS.white,
    fontFamily: "Poppins-Regular",
    textAlign: "center",
  },
  userPipokaCount: {
    fontSize: height * 0.024,
    fontFamily: "Poppins-SemiBold",
  },
  userPipokaIconWrapper: {
    width: height * 0.06,
    height: height * 0.06,
    borderRadius: height * 0.03,
    borderColor: COLORS.primaryDark,
    borderWidth: height * 0.005,
    position: "absolute",
    backgroundColor: COLORS.gold,
    alignItems: "center",
    right: -5,
    justifyContent: "center",
  },
  userPipokaIcon: {
    width: "70%",
    height: "70%",
  },
});

