import { StyleSheet } from 'react-native';
import { Dimensions } from 'react-native';
const { height } = Dimensions.get('window');

export const style = StyleSheet.create({
    background: {
        flex: 1,
        width: '100%',
        height: '100%',
        backgroundColor: '#B22300',
        alignItems: 'center',
        justifyContent: 'flex-start',
        paddingTop: height * 0.05,
    },
    center: {
        alignItems: 'center',
        marginTop: height * 0.01,
    },
    box: {
        backgroundColor: '#B22300',
        borderRadius: 20, 
        alignSelf: 'center',
        boxShadow: '0px 4px 40px 40px rgba(0, 0, 0, 0.20)', 
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.25,
        shadowRadius: 15.8,
        elevation: 16, 
        overflow: 'visible',
    },
    logo: {
        marginTop: height * 0.05,
        marginBottom: height * 0.05,
        height: height * 0.23,
        resizeMode: 'contain',
    },
    popcorn: {
        position: 'absolute',
        width: height * 0.07,
        height: height * 0.07,
        top: -height * 0.04,
        zIndex: 10,
        alignSelf: 'center',
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'white',
        borderRadius: 50,
        paddingHorizontal: 15,
        height: height * 0.06,
        width: '90%',
        marginVertical: height * 0.015,
        borderWidth: height * 0.005,
        borderColor: '#FE481B',
    },
    inputIcon: {
        width: '6%',
        height: '50%',
        marginRight: 10,
        tintColor: '#A9A9A9',
    },
    inputText: {
        flex: 1,
        fontSize: height * 0.018,
        color: '#A9A9A9',
        fontFamily: 'Poppins-SemiBold',
    },
    formContainer: {
        position: 'absolute',
        top: '10%',
        width: '100%',
        height: '100%',
        alignItems: 'center',
    },
    esqueceuSenhaContainer: {
        alignSelf: 'flex-end',
        marginRight: '8%',
        marginTop: 10,
    },
    esqueceuSenha: {
        fontSize: height * 0.016,
        color: '#FFFEB2',
        marginBottom: height * 0.01,
        fontFamily: 'Poppins-SemiBold',
        textDecorationLine: 'underline',
    },
    button: {
        borderRadius: 50,
        height: height * 0.06,
        width: '50%',
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        marginTop: height * 0.01,
        marginBottom: height * 0.03,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
    },
    buttonText: {
        fontFamily: 'Poppins-SemiBold',
        fontSize: height * 0.027,
    },
    buttonY: {
        backgroundColor: '#FFFEB2',
        color: '#000',
    },
    buttonB: {
        backgroundColor: '#000000',
        color: '#FFFEB2',
    },
    message: {
        fontSize: height * 0.016,
        color: '#FFFEB2',
        fontFamily: 'Poppins-SemiBold',
    },
});