import { StyleSheet } from "react-native";
import { Dimensions } from "react-native";
import { Platform } from "react-native";
const { height } = Dimensions.get("window");

export const style = StyleSheet.create({
  background: {
    flex: 1,
    width: "100%",
    height: "100%",
    backgroundColor: "#B22300",
    alignItems: "center",
    justifyContent: "flex-start",
  },
  center: {
    alignItems: "center",
    marginTop: height * 0.01,
  },
  box: {
    backgroundColor: "#B22300",
    borderRadius: 30,
    alignSelf: "center",
    boxShadow: "0px 4px 40px 40px rgba(0, 0, 0, 0.20)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 15.8,
    elevation: 16,
    overflow: "visible",
  },
  formContainer: {
    paddingTop: height * 0.02,
    width: "100%",
    height: "75%",
    alignItems: "center",
    paddingBottom: 20,
  },
  logoS: {
    marginTop: height * 0.01,
    marginBottom: height * 0.01,
    height: height * 0.1,
    resizeMode: "contain",
  },
  logoB: {
    marginTop: height * 0.1,
    marginBottom: height * 0.05,
    height: height * 0.23,
    resizeMode: "contain",
  },
  logoM: {
    marginTop: height * 0.03,
    marginBottom: height * 0.04,
    height: height * 0.18,
    resizeMode: "contain",
  },
  popcorn: {
    position: "absolute",
    width: height * 0.07,
    height: height * 0.07,
    top: -height * 0.04,
    zIndex: 10,
    alignSelf: "center",
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    borderRadius: height*0.03,
    paddingHorizontal: 15,
    height: height * 0.06,
    width: "90%",
    marginVertical: height * 0.01,
    borderWidth: height * 0.005,
    borderColor: "#FE481B",
  },
  inputIcon: {
    width: "6%",
    height: "50%",
    marginRight: 10,
    tintColor: "#A9A9A9",
  },
  inputText: {
    flex: 1,
    fontSize: height * 0.015,
    color: "#A9A9A9",
    fontFamily: "Poppins-SemiBold",
  },
  esqueceuSenhaContainer: {
    alignSelf: "flex-end",
    marginRight: "8%",
    marginTop: 10,
  },
  esqueceuSenha: {
    fontSize: height * 0.016,
    color: "#FFFEB2",
    marginBottom: height * 0.01,
    fontFamily: "Poppins-SemiBold",
    textDecorationLine: "underline",
  },
  button: {
    borderRadius: height * 0.03,
    height: height * 0.06,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    marginTop: height * 0.01,
    marginBottom: height * 0.01,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 15 },
    shadowOpacity: 0.25,
    shadowRadius: height * 0.0158,
  },
  buttonText: {
    fontFamily: "Poppins-SemiBold",
    fontSize: height * 0.027,
    textAlign: "center",
  },
  buttonY: {
    width: "50%",
    backgroundColor: "#FFFEB2",
    boxShadow: "0px 10px 20px 20px rgba(0, 0, 0, 0.20)",
  },
  buttonYText: {
    color: "#000000",
  },
  buttonBText: {
    color: "#FFFEB2",
  },
  buttonB: {
    backgroundColor: "#000000",
    width: "50%",
    boxShadow: "0px 10px 20px 20px rgba(0, 0, 0, 0.20)",
  },
  buttonVoltar: {
    width: "30%",
    boxShadow: "0px 9px 20px 15px rgba(0, 0, 0, 0.20)",
    shadowColor: "#000",
    backgroundColor: "#000000",
  },
  buttonVoltarText: {
    color: "#FFFEB2",
    fontFamily: "Poppins-SemiBold",
    fontSize: height * 0.027,
    textAlign: "center",
  },
  buttonGenre: {
    borderRadius: height * 0.06,
    paddingHorizontal: height * 0.02,
    paddingVertical: height * 0.01,
    marginVertical: height * 0.01,
    marginHorizontal: height * 0.005,
    boxShadow: "0px 9px 20px 10px rgba(0, 0, 0, 0.20)",
    backgroundColor: "#000000",
  },
  buttonGenreText: {
    color: "#FFFEB2",
    fontFamily: "Poppins-SemiBold",
    fontSize: height * 0.02,
    textAlign: "center",
    borderRadius: 50,
  },
  genresContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    width: "95%",
    marginTop: height * 0.02,
  },
  message: {
    fontSize: height * 0.014,
    color: "#FFFEB2",
    fontFamily: "Poppins-SemiBold",
    textAlign: "center",
  },
  text: {
    fontSize: height * 0.022,
    maxWidth: "90%",
    color: "#FFFEB2",
    fontFamily: "Poppins-SemiBold",
    textAlign: "center",
  },
  iconPerfilContainer: {
    height: height * 0.15,
    width: height * 0.15,
    borderRadius: (height * 0.15) / 2,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
    marginBottom: 10,
    alignSelf: "center",
    position: "relative",
    borderWidth: 4,
    borderColor: "#FE481B",
  },
  iconPerfilImage: {
    height: "100%",
    width: "100%",
    borderRadius: (height * 0.15) / 2,
    resizeMode: "contain",
  },
  editButtonContainer: {
    position: "absolute",
    bottom: 0,
    right: -height * 0.15 * 0.1,
    height: height * 0.15 * 0.35,
    width: height * 0.15 * 0.35,
    backgroundColor: "#000000",
    borderRadius: "100%",
    borderWidth: height * 0.004,
    borderColor: "#FFFEB2",
    justifyContent: "center",
    alignItems: "center",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  editButtonIcon: {
    width: "90%",
    height: "90%",
    resizeMode: "contain",
    tintColor: "#FFFEB2",
  },

  navbarWrapper: {
    width: "100%",
    minHeight: 350,
    height: Platform.OS === "web" ? 360 : 350,
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 999,
    justifyContent: "flex-end",
    alignItems: "center",
  },
  navbarContainer: {
    width: "90%",
    height: 230,
    backgroundColor: "#B22300",
    borderRadius: 32,
    shadowColor: "#000",
    shadowOpacity: 0.5,
    shadowRadius: 50,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
    overflow: "hidden",
    zIndex: 2,
    marginBottom: Platform.OS === "ios" ? 20 : 15,
  },
  navbarBackground: {
    position: "absolute",
    bottom: 0,
    width: "115%",
    height: 450,
    top: -60,
    left: "50%",
    transform: [{ translateX: "-50%" }],
    zIndex: 1,
  },
  safeArea: {
    flex: 1,
    backgroundColor: "transparent",
    zIndex: 2,
    paddingTop: 15,
    paddingBottom: Platform.OS === "ios" ? 30 : 20,
  },
  tabContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    marginHorizontal: 20,
    paddingBottom: Platform.OS === "ios" ? 20 : 15,
  },
  tab: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 8,
  },
  tabContent: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 5,
  },
  activeTabContent: {
    backgroundColor: "#FFFEB2",
    width: 185,
    height: 185,
    borderRadius: 90,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  iconWrapper: {
    width: 120,
    height: 120,
    borderRadius: 60,
    alignItems: "center",
    justifyContent: "center",
  },
  imageIcon: {
    width: 70,
    height: 70,
    tintColor: "#FFFEB2",
  },
  activeImageIcon: {
    tintColor: "#D42A23",
  },
  label: {
    fontSize: 24,
    fontFamily: "Poppins-SemiBold",
    color: "#FFFEB2",
    marginTop: 2,
  },
  activeLabel: {
    color: "#B22300",
    fontFamily: "Poppins-SemiBold",
  },
});
