import { StyleSheet } from 'react-native';
import { Dimensions } from 'react-native';
const { height } = Dimensions.get('window');

export const style = StyleSheet.create({
    background: {
        flex: 1,
        width: '100%',
        height: '100%',
        backgroundColor: '#B22300',
        alignItems: 'center',
        justifyContent: 'flex-start',
        paddingTop: height * 0.05,
    },
    center: {
        alignItems: 'center',
        marginTop: height * 0.01,
    },
    box: {
        backgroundColor: '#B22300',
        borderRadius: 30, 
        alignSelf: 'center',
        boxShadow: '0px 4px 40px 40px rgba(0, 0, 0, 0.20)', 
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.25,
        shadowRadius: 15.8,
        elevation: 16, 
        overflow: 'visible',
    },
    formContainer: {
        position: 'absolute',
        top: height * 0.025,
        width: '100%',
        height: '75%',
        alignItems: 'center',
        paddingBottom: 20
    },
    logoS: {
        marginTop: height * 0.0,
        marginBottom: height * 0.01,
        height: height * 0.1,
        resizeMode: 'contain',
    },
    logoB: {
        marginTop: height * 0.05,
        marginBottom: height * 0.05,
        height: height * 0.23,
        resizeMode: 'contain',
    },
    popcorn: {
        position: 'absolute',
        width: height * 0.07,
        height: height * 0.07,
        top: -height * 0.04,
        zIndex: 10,
        alignSelf: 'center',
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'white',
        borderRadius: 50,
        paddingHorizontal: 15,
        height: height * 0.065,
        width: '90%',
        marginVertical: height * 0.010,
        borderWidth: height * 0.005,
        borderColor: '#FE481B',
    },
    inputIcon: {
        width: '6%',
        height: '50%',
        marginRight: 10,
        tintColor: '#A9A9A9',
    },
    inputText: {
        flex: 1,
        fontSize: height * 0.015,
        color: '#A9A9A9',
        fontFamily: 'Poppins-SemiBold',
    },
    esqueceuSenhaContainer: {
        alignSelf: 'flex-end',
        marginRight: '8%',
        marginTop: 10,
    },
    esqueceuSenha: {
        fontSize: height * 0.016,
        color: '#FFFEB2',
        marginBottom: height * 0.01,
        fontFamily: 'Poppins-SemiBold',
        textDecorationLine: 'underline',
    },
    button: {
        borderRadius: 50,
        height: height * 0.06,
        width: '50%',
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        marginTop: height * 0.01,
        marginBottom: height * 0.03,
        elevation: 5,
        boxShadow: '0px 10px 20px 30px rgba(0, 0, 0, 0.20)', 
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 15 },
        shadowOpacity: 0.25,
        shadowRadius: 15.8,
    },
    buttonText: {
        fontFamily: 'Poppins-SemiBold',
        fontSize: height * 0.027,
    },
    buttonY: {
        backgroundColor: '#FFFEB2',
        color: '#000',
    },
    buttonB: {
        backgroundColor: '#000000',
        color: '#FFFEB2',
    },
    buttonVoltar: {
        borderRadius: 50,
        height: height * 0.06,
        width: '30%',
        justifyContent: 'center',
        alignSelf: 'center',
        elevation: 5,
        boxShadow: '0px 10px 20px 30px rgba(0, 0, 0, 0.20)', 
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 15 },
        shadowOpacity: 0.25,
        shadowRadius: 15.8,
        backgroundColor: '#000000',
    },
    buttonVoltarText: {
        color: '#FFFEB2',
        fontFamily: 'Poppins-SemiBold',
        fontSize: height * 0.027,
        textAlign: 'center',
    },
    message: {
        fontSize: height * 0.014,
        color: '#FFFEB2',
        fontFamily: 'Poppins-SemiBold',
        textAlign: 'center',
        paddingHorizontal: '3%',
    },
    text: {
        fontSize: height * 0.020,
        color: '#FFFEB2',
        fontFamily: 'Poppins-SemiBold',
        textAlign: 'center',
    },
    iconPerfilContainer: {
        height: height * 0.15,
        width: height * 0.15,
        borderRadius: (height * 0.15) / 2,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 10,
        marginBottom: 10,
        alignSelf: 'center',
        position: 'relative',
        borderWidth: 4,
        borderColor: '#FE481B'
    },
    iconPerfilImage: {
        height: '100%',
        width: '100%',
        borderRadius: (height * 0.15) / 2,
        resizeMode: 'contain',
    },
    editButtonContainer: {
        position: 'absolute',
        bottom: 0,
        right: -height * 0.15 * 0.1,
        height: height * 0.15 * 0.35,
        width: height * 0.15 * 0.35,
        backgroundColor: '#000000',
        borderRadius: '100%',
        borderWidth: height * 0.004,
        borderColor: '#FFFEB2',
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
    },
    editButtonIcon: {
        width: '90%',
        height: '90%',
        resizeMode: 'contain',
        tintColor: '#FFFEB2',
    },
});

